/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : ADXL362 Shake Awake Implementation
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "adxl362.h"
#include "config.h"

/* STM32L432 Register Definitions */
#define RCC_BASE        0x40021000
#define GPIOA_BASE      0x48000000
#define GPIOB_BASE      0x48000400
#define USART2_BASE     0x40004400
#define NVIC_BASE       0xE000E100

typedef struct {
    volatile uint32_t CR;
    volatile uint32_t ICSCR;
    volatile uint32_t CRRCR;
    volatile uint32_t CFGR;
    volatile uint32_t PLLCFGR;
    volatile uint32_t PLLSAI1CFGR;
    volatile uint32_t PLLSAI2CFGR;
    volatile uint32_t CIER;
    volatile uint32_t CIFR;
    volatile uint32_t CICR;
    volatile uint32_t AHBSR;
    volatile uint32_t RESERVED;
    volatile uint32_t AHB1RSTR;
    volatile uint32_t AHB2RSTR;
    volatile uint32_t AHB3RSTR;
    volatile uint32_t RESERVED2;
    volatile uint32_t APB1RSTR1;
    volatile uint32_t APB1RSTR2;
    volatile uint32_t APB2RSTR;
    volatile uint32_t RESERVED3;
    volatile uint32_t AHB1ENR;
    volatile uint32_t AHB2ENR;
    volatile uint32_t AHB3ENR;
    volatile uint32_t RESERVED4;
    volatile uint32_t APB1ENR1;
    volatile uint32_t APB1ENR2;
    volatile uint32_t APB2ENR;
} RCC_TypeDef;

typedef struct {
    volatile uint32_t MODER;
    volatile uint32_t OTYPER;
    volatile uint32_t OSPEEDR;
    volatile uint32_t PUPDR;
    volatile uint32_t IDR;
    volatile uint32_t ODR;
    volatile uint32_t BSRR;
    volatile uint32_t LCKR;
    volatile uint32_t AFRL;
    volatile uint32_t AFRH;
} GPIO_TypeDef;

typedef struct {
    volatile uint32_t CR1;
    volatile uint32_t CR2;
    volatile uint32_t CR3;
    volatile uint32_t BRR;
    volatile uint32_t GTPR;
    volatile uint32_t RTOR;
    volatile uint32_t RQR;
    volatile uint32_t ISR;
    volatile uint32_t ICR;
    volatile uint32_t RDR;
    volatile uint32_t TDR;
} USART_TypeDef;

typedef struct {
    volatile uint32_t ISER[8];
} NVIC_Type;

#define RCC         ((RCC_TypeDef *) RCC_BASE)
#define GPIOA       ((GPIO_TypeDef *) GPIOA_BASE)
#define GPIOB       ((GPIO_TypeDef *) GPIOB_BASE)
#define USART2      ((USART_TypeDef *) USART2_BASE)
#define NVIC        ((NVIC_Type *) NVIC_BASE)

/* UART Printf 支持 */
int _write(int file, char *ptr, int len) {
    for (int i = 0; i < len; i++) {
        while (!(USART2->ISR & (1 << 7))) {} /* 等待 TXE */
        USART2->TDR = ptr[i];
    }
    return len;
}

/* UART2 初始化 */
static void UART2_Init(void) {
    /* 使能GPIOA和USART2时钟 */
    RCC->AHB2ENR |= (1 << 0);   /* GPIOA */
    RCC->APB1ENR1 |= (1 << 17); /* USART2 */
    
    /* PA2 (TX), PA3 (RX) 配置为AF07 */
    GPIOA->MODER &= ~(0x3 << 4);
    GPIOA->MODER |= (0x2 << 4);  /* PA2 alternate function */
    GPIOA->AFRL &= ~(0xF << 8);
    GPIOA->AFRL |= (0x7 << 8);   /* AF7 for USART2 */
    
    GPIOA->MODER &= ~(0x3 << 6);
    GPIOA->MODER |= (0x2 << 6);  /* PA3 alternate function */
    GPIOA->AFRL &= ~(0xF << 12);
    GPIOA->AFRL |= (0x7 << 12);  /* AF7 for USART2 */
    
    /* USART2配置 (9600 baud @ 4MHz) */
    USART2->CR1 = 0x0000;
    USART2->BRR = 0x00D0;  /* 9600 baud */
    USART2->CR1 |= (1 << 3);    /* TE - Transmitter Enable */
    USART2->CR1 |= (1 << 2);    /* RE - Receiver Enable */
    USART2->CR1 |= (1 << 0);    /* UE - USART Enable */
}

/* 简单延迟 */
static void Delay(uint32_t ms) {
    volatile uint32_t count = ms * DELAY_MULTIPLIER;
    while (count--) {}
}

/* INT2中断处理 (PB6) */
volatile uint8_t shake_detected = 0;

static void EXTI_Init(void) {
    /* 使能GPIOB时钟 */
    RCC->AHB2ENR |= (1 << 1);   /* GPIOB */
    
    /* PB6配置为输入（已在ADXL362初始化中配置）*/
    GPIOB->MODER &= ~(0x3 << 12);
    GPIOB->MODER |= (0x0 << 12); /* Input mode */
    
    /* 简单的轮询实现中断检测 */
}

/* PA11输出控制 */
static void Output_SetHigh(void) {
    GPIOA->ODR |= (1 << 11);
}

static void Output_SetLow(void) {
    GPIOA->ODR &= ~(1 << 11);
}

/* 主程序 */
int main(void) {
    UART2_Init();
    EXTI_Init();
    
    printf("\r\n========================================\r\n");
    printf("ADXL362 Shake Awake Demo\r\n");
    printf("========================================\r\n");
    printf("Initializing ADXL362...\r\n");
    
    /* 初始化ADXL362，阈值设为300mg */
    ADXL362_Init(ADXL362_THRESHOLD_MG);
    
    printf("ADXL362 Initialized\r\n");
    printf("Threshold: %dmg\r\n", ADXL362_THRESHOLD_MG);
    printf("Waiting for shake events...\r\n");
    printf("========================================\r\n\r\n");
    
    ADXL362_Data_t accel_data;
    uint32_t counter = 0;
    uint8_t prev_int2_state = 0;
    
    while (1) {
        /* 读取INT2状态 (PB6) */
        uint8_t int2_state = (GPIOB->IDR >> 6) & 0x01;
        
        /* 检测INT2的上升沿 */
        if (int2_state && !prev_int2_state) {
            shake_detected = 1;
            Output_SetHigh();  /* 设置PA11为高 */
        }
        
        prev_int2_state = int2_state;
        
        /* 每次迭代读取加速度数据 */
        ADXL362_ReadData(&accel_data);
        
        /* 每100次迭代（约100ms）输出一次数据 */
        if (++counter >= 100) {
            counter = 0;
            
            float x_g = ADXL362_ConvertToG(accel_data.x);
            float y_g = ADXL362_ConvertToG(accel_data.y);
            float z_g = ADXL362_ConvertToG(accel_data.z);
            
            printf("X: %5.2f G | Y: %5.2f G | Z: %5.2f G", x_g, y_g, z_g);
            
            if (shake_detected) {
                printf(" [SHAKE DETECTED]");
                Output_SetLow();   /* 清除PA11 */
                shake_detected = 0;
            }
            printf("\r\n");
        }
        
        Delay(1);  /* 1ms延迟 */
    }
    
    return 0;
}
